### ISSUE TITLE
HTML symbols escape in user data

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#1222]
Create a VM with the following user-data:

```yaml
#cloud-config
manage_etc_hosts: "localhost"
runcmd:
- #!/bin/sh
- exec > /tmp/userdata.log
- exec 2>&1
- echo "Hello, world"
```

Inside the server you'll see:

```
# cat /var/lib/cloud/instance/scripts/runcmd 
#!/bin/sh
set -x
exec &gt; /tmp/userdata.log
exec 2&gt;&amp;1
echo "Hello, world"
```
