### ISSUE TITLE
[Task](CI):  set up a helm-dep-up job in the pipeline to reduce creating a PR to update the chart.lock with new versions

### ISSUE THREAD

**Issue by ArtieReus** [sapcc/elektra#1415]
**Task Description**
Set up a helm-dep-up job in the pipeline to reduce creating a PR to update the chart.lock with new versions. See 
- similar job in the keppel pipeline between lines L325-L342
- slack [discussion](https://convergedcloud.slack.com/archives/C2WPEPV8B/p1726664937998779)

**Sub-tasks**

- [ ] Extend elektra pipelline to add weekly helm-dep-up job.

**Related Issues**
Link to related issues or tasks, if any.

**Additional Context**
Add any other context or information here.

**Comment by hgw77** [comment]
the task will trigger next monday between 6 and 10

````yaml
  - name: every-week
    type: time
    icon: clock-outline
    check_every: 1h
    source:
      days: [Monday]
      location: Europe/Berlin
      start: 06:00 AM
      stop: 10:00 AM
````
