### ISSUE TITLE
Feat(Identity): made terms of use configurable per domain

### ISSUE THREAD

**Issue by hgw77** [sapcc/elektra#1464]
We need a possibility to have the option to setup terms of use per domain.

We can adjust the domain_config to disable TermsOfUse with
````
domains:
  - name: test
    regex: "testtest"
    disabled_features:
      - terms_of_use
 ````
to have extra terms of use for special domain
````
domains:
  - name: test
    regex: "testtest"
    terms_of_use:
      - version: "1.0"
        name: "tou_for_test"
````
